spring:
  datasource:
    url: jdbc:mysql://database-gdam2-2.cv5zox3zgfa3.us-east-1.rds.amazonaws.com:3306/biblioteca
    username: admin
    password: Admin1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect